def eat(breakfast, lunch, dinner = "カレー"):
    print(f"{breakfast}を食べました")
    print(f"{lunch}を食べました")
    print(f"{dinner}を食べました")
print("8月1日")
eat("トースト","おにぎり")
print("8月2日")
eat("納豆ごはん","ラーメン")
print("8月3日")
eat("バナナ","そば","焼肉")
print("8月4日")
eat("サンドウィッチ","しゅうまい弁当")